spring.application.name=Freelance-System
spring.datasource.url=jdbc:mysql://localhost:3306/freelance_db
spring.datasource.username=root
spring.datasource.password=eBIE@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
